### ISSUE TITLE
small fixes to city file

### ISSUE THREAD

**Issue by fiannuzzi** [Stanislas-Poisson/French-zip-code#14]
Hello! First of all, thank you so much for this resource. I just point out a couple little 'bugs' in cities.csv that I came across:

1) the last 3 rows contain commas instead of semicolons;
2) the "slug" and "pattern" versions of "Lüe" are "le" instead of "lue".
(In python, I obtain "lue" via unicodedata.normalize("NFKD", "Lüe").encode('ascii', 'ignore').decode('ascii') - just in case).

Cheers!

**Comment by Stanislas-Poisson** [comment]
Hi @fiannuzzi 
Thanks for reporting this mistake. I will do my best for check if another mistake was hide inside and rebuild the database :)
You're welcome to work on it :)

**Comment by Stanislas-Poisson** [comment]
Thanks for this reporting.
Corrected in the #16 and publish in the release v1.2.0.
