### ISSUE TITLE
"Le Theil": wrong postal code

### ISSUE THREAD

**Issue by Otiel** [Stanislas-Poisson/French-zip-code#17]
At the following line:
```
24235;62;"Le Theil";"le-theil";"le theil";"61P19";48.2639;0.688
```
Postal code is "61P19" instead of "61260".

**Comment by Stanislas-Poisson** [comment]
Thanks, I soon take care of it.

**Comment by Stanislas-Poisson** [comment]
Just make in the #20 
Working on the #19 then a realease will be make.
