### ISSUE TITLE
Typo? Haute Savoie ? 

### ISSUE THREAD

**Issue by jul** [Stanislas-Poisson/French-zip-code#23]
import json 
dep = json.loads(requests.get("https://raw.githubusercontent.com/Stanislas-Poisson/French-zip-code/master/JSON/departments.json").text)
DDPT = { e["code"] : e["name"] for e in dep }

#In [54]: DDPT["74"]
# Out[54]: 'Haut-Savoie'

Je parie sur Haute-Savoie

**Comment by Stanislas-Poisson** [comment]
Effectivement.
Je corrige dans la journée.

Je prépare une version 2 à partir des données de l’INSEE accompagner d'un builder cela prend du temps de bien le faire mais permettras a tous de pouvoir faire les mise a jour plus facilement.

**Comment by Stanislas-Poisson** [comment]
Down in the last release 1.3.1
