### ISSUE TITLE
"Thièvres" Wrong Zipcode 

### ISSUE THREAD

**Issue by Carboxyde** [Stanislas-Poisson/French-zip-code#31]
There are 2 "Thièvres" in the cities:

24861,62,62814,62760,Thièvres,thievres,50.132551851852,2.4468190740741
and
32410,80,80756,62760,Thièvres,thievres,50.120079733333,2.4628542666667

The Zipcode for the second one is supposed to be 80560, not the same as the first one

**Comment by Stanislas-Poisson** [comment]
Hi, I don't know were you found this zipcode **80560** all the services used _they are pretty official_ answer the zipcode **62760**.
- [api-adresse.data.gouv.fr](http://api-adresse.data.gouv.fr/search/?q=Thi%C3%A8vres&type=municipality)
- [www..google.fr](https://www.google.fr/search?q=Thi%C3%A8vres%2C+Somme%2C+France&oq=Thi%C3%A8vres%2C+Somme%2C+France&aqs=chrome..69i57j69i60l3.8701j0j1&sourceid=chrome&ie=UTF-8)
- [nominatim.openstreetmap.org](https://nominatim.openstreetmap.org/search?q=Thi%C3%A8vres%2C+Somme%2C+France&format=json&addressdetails=1)
- ![geoportail-thievres-somme-france](https://user-images.githubusercontent.com/3681410/42676426-74be9c06-8678-11e8-8a3b-df30a2916de6.png)

I don't think of changing it for now, all of this repo used the data of INSEE and services that are pretty official in the builder.

Can you let me know were you found this zipcode ? Maybe it's official but for the next year.

**Comment by Carboxyde** [comment]
I think it must be a common error, but "Somme" department's code is 80 so the zipcode cannot start with 62.That's what made me search on the wikipédia page and it was there : https://fr.wikipedia.org/wiki/Thi%C3%A8vres_(Somme)
![image](https://user-images.githubusercontent.com/15823859/42678581-9aaeb156-867f-11e8-9db4-26e96e9caf78.png)

It seems that it changed in 2017 : http://www.lavoixdunord.fr/99554/article/2017-01-07/apres-deux-siecles-d-existence-le-village-obtient-enfin-son-propre-code-postal

**Comment by Stanislas-Poisson** [comment]
It look like but many cities have their zipcode with another department code (Already answered for a previous version by @Otiel on the #19 ) https://fr.wikipedia.org/wiki/Liste_des_communes_de_France_dont_le_code_postal_ne_correspond_pas_au_d%C3%A9partement

Thièvres in the department 80 has officialy the zipcode **62760**. When it officialy change, the database will change too, but for now Wikipédia and la voix du nord are not an official way to have the zip code.

Edit: Just found this page https://www.data.gouv.fr/es/territories/commune/80756@1942-01-01/Thievres/ wich also say **62760**.
